### ISSUE TITLE
compatibility with iron-router 1.0

### ISSUE THREAD

**Issue by dohomi** [yoolab/iron-router-i18n#19]
Hello @martinopic 
is the 0.4.3 version already compatible with iron-router 1.0? Just read about it yesterday and wanted to ask first before I bump in too many issues. Feel free to use the previous test package for some tests. Cheers

**Comment by dohomi** [comment]
Hello @martinopic do you have any news on this? Happy New Year :rocket:

**Comment by LarsBuur** [comment]
I will happily try to assist in testing / debugging the 1.0 package. It is currently not a must have for me - but a nice to have. Happy new year!

**Comment by zimt28** [comment]
Need this as well for other dependencies /:

**Comment by martinopic** [comment]
I'm really sorry for the delay on keeping up with this I hoped to work on it during Christmas time but couldn't. I'll start to work on it next week and hope to have it completed in a couple of weeks, I'll keep you updated here (and on the codebase) and put a ote on the README.

**Comment by zimt28** [comment]
Thank you for working on this :)

**Comment by txs** [comment]
Really need this package! Excited about it!

**Comment by martinopic** [comment]
Hi everybody,

I've just pushed a 0.5.x branch which contains a first version compatible with iron:router 1.0. This version pass all previous client side tests (test system has also been improved) excluding template name resolution tests. No server side functionality is still in place.

I have just tested it with automatic tests, any feedback on "real" systems will be welcome as any other useful contribution (consider this is still alpha quality code). In the next few days I hope to complete the client and server part.

The improvements made on iron:router apparently allowed also iron-router-18n to have cleaner code and testing.

Thanks for the patience, hope a stable release is coming soon :-)

**Comment by martinopic** [comment]
With las commit on 0.5.x almost all client tests are passing (including template name resolution), just missing redirect on missing lang code testing and server side functionality. And real world system test obviously.

**Comment by dohomi** [comment]
Hi @martinopic nice that you got some time to work on this, I appreciate it. For now I checked out the branch and started with updating my whole app. As its quite grown up I think its gonna be a little workout..

I moved all my routes to the lib folder making them accassible for client and server. I'm getting plenty of: Oops, looks like there's no route on the client or the server for url: 

And plenty of 
```
Created route:
router.js:135 client
router.js:136 undefined
```
What are these messages about?

**Comment by martinopic** [comment]
Hi @dohomi, the second issue you mention should be solved with last commit. There is still a big issue which is probably causing the missing route problem, should be the last one and not that hard to fix. It would be useful if you could paste me here a small excerpt of the not working conf (e.g. some route not found but actually configured).

**Comment by martinopic** [comment]
All tests passing (I've added some more), all features there (plus some new one) and configuration/behaviour almost identical to version 0.4.x and supporting new Iron Router 1.0.x configuration methods. I had to change/remove some configuration stuff (will be documented).

Almost ready to release (I'd really like some feedback before releasing).

**Comment by dohomi** [comment]
Hi @martinopic I tried the current commits. I still receive the 
```
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/en/login.
```
And following error:
```
 Exception in template helper: TypeError: Cannot read property 'getRouteForLang' of undefined
    at Object.<anonymous> (http://localhost:3000/packages/martino_iron-router-i18n.js?4a48b123b5103913fa2507db99f00eeb4bb1361b:599:29)
```

**Comment by martinopic** [comment]
@dohomi for the first issue I need your configuration (at least the basic non working part).

As for the second issue if you were using the "old" syntax (`{{pathFor route="myRoute"}}`) I fixed that with the last commit, otherwise it just seems a non existing route name. 

Thanks for your feedback!

**Comment by dohomi** [comment]
hi @martinopic what do you mean with "old" syntax? ```pathFor route="myRoute"``` is not the current syntax? https://github.com/EventedMind/iron-router/blob/devel/Guide.md#pathfor


```
// config

TP.Core.Functions.setLanguageKey = function (lang) {
  Helpers.setLanguage(lang);
};

Router.configure({
  layoutTemplate: 'layoutBackend',
  loadingTemplate: 'loading',
  notFoundTemplate: "page404",
  i18n: {
    languages: TP.Const.AllowedLangKey,

    setLanguage: function (lang) {
      if (Meteor.isClient) {
        TP.Core.Functions.setLanguageKey(lang);
      }
    },
    autoConfLanguage: true
  }
});

```

This is my current configuration

**Comment by martinopic** [comment]
You are right @dohomi I was using the old conf :-) in any case now both work for the helpers.

As for the other problem:

1) What's in `TP.Const.AllowedLangKey` ?
2) Can I have the login (or any failing) route configuration?

**Comment by dohomi** [comment]
Hi @martinopic, 
Sorry here the missing configuration:
```
TP.Const.AllowedLangKey = [
  'en', 'de'
];

Router.onBeforeAction('loading');
Router.onBeforeAction('dataNotFound');

Router.route("/login", {
  path: "/login",
  name: "login",
  template: "loginForm",
  layoutTemplate: "layoutLogin"
});

```

Do you know if the old style ```Router.map(function(){this.route( ... )}```is still valid?

**Comment by martinopic** [comment]
Hi @dohomi , this is really an edge case: you are passing the path through the route name (new configuration) AND through the path option, kind of redundant but this was the reason it was failing. I've fixed the code (and added tests) to handle also this edge case and added tests for legacy `Router.map` configuration (which works ;-) ). Thanks for the feedback!

I've added a basic example app in `examples/basic` it anybody wants to test or give feedback about bugs about can also use this basic app adding the configuration which shows the bug.

If nobody else is reporting problems and @dohomi app is working I'm going to release soon.

**Comment by dohomi** [comment]
Hey @martinopic actually for me is the whole upgrade from iron:router 1.x somehow not really clear what actually was changing. The docs are not very specific, I was always writing Router.map(...), so I just played around with all values actually :)

I receive now a ``` Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?```message, so I need to fix that first. Damn lot of code changes :/

**Comment by dohomi** [comment]
I have the feeling that currently your package works fine, I need to check all my iron router hooks first

**Comment by dohomi** [comment]
Hi @martinopic I rewrote lot of code. I don't receive any error messages anymore beside the big fat:
```
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/en/login."
```
Even the page is getting rendered correctly, but there seems still a problem with the config. Here my adjusted config:
```
// config
Router.configure({
  layoutTemplate: 'layoutBackend',

  i18n: {
    languages: TP.Const.AllowedLangKey,

    setLanguage: function (lang) {
      if (Meteor.isClient) {
        TP.Core.Functions.setLanguageKey(lang);
      }
    },
    autoConfLanguage: true
  }
});
Router.plugin('dataNotFound', {notFoundTemplate: 'notFoundTemplate'});
Router.plugin('loading', {loadingTemplate: 'loading'});

Router.setTemplateNameConverter(function (str) {
  return str;
});


Router.route("/login", {
  name: "login",
  template: "loginForm",
  layoutTemplate: "layoutLogin"
});

```

**Comment by dohomi** [comment]
Hi @martinopic 

I adjusted now all my routes for the new 1. of ```iron:router```. Without this package every route worked as expected. 

Now, as soon I activate this package the ```__IronRouterNoRoutes__```is getting rendered above my whole app. I don't receive any other errors, but I'm getting the message of no routes found. But my 2 routes, login and home are linked correctly and rendered correctly behind the iron:router message. So ```pathFor```works in this case..

I'm finishing for now, will continue tomorrow with further testing. Please drop me a message if you have any idea. This is my current configuration:

```

Router.configure({
  layoutTemplate: 'layoutBackend',
  notFoundTemplate: 'page404',
  loadingTemplate: 'loading',
  i18n: {
    languages: TP.Const.AllowedLangKey,

    setLanguage: function (lang) {
      if (Meteor.isClient) {
        TP.Core.Functions.setLanguageKey(lang);
      }
    },
    autoConfLanguage: true
  }
});

Router.plugin('dataNotFound', {notFoundTemplate: 'page404'});
Router.plugin('loading', {loadingTemplate: 'loading'});


Router.route("/login", {
  name: "login",
  template: "loginForm",
  layoutTemplate: "layoutLogin"
});
```


Cheers

**Comment by dohomi** [comment]
Hello,

I tried to testrun the ```Tinytest```with the ```meteor test-packages martino:iron-router-i18n``` command. All test seems to be fine, but on the bottom of the page ```iron:router```renders the ```__IronRouterNoRoutes__``` template on the bottom of the page.

It seems that all routes of iron:router looses all routes and also doesn't find the notFoundTemplate:

```
 var notFoundTemplate = this.lookupOption('notFoundTemplate');

          if (!notFoundTemplate)
            notFoundTemplate = (self.routes.length === 0) ? NO_ROUTES_TEMPLATE : DEFAULT_NOT_FOUND_TEMPLATE;
```
The website renders but it renders twice.. and in the second run it adds the ```NO_ROUTES_TEMPLATE```

**Comment by martinopic** [comment]
Hi @dohomi thanks a lot for your feedback and testing I spotted a major problem in the router startup which is causing this, working on it.

**Comment by martinopic** [comment]
@dohomi can you test now? It should be fixed.

**Comment by dohomi** [comment]
@martinopic yes I just did :+1: perfect man thanks! All my previous errors are gone, still I couldn't test everything. Will drop you a note if I bump into any issue with it. 

Where would you define defaultLanguage now based on a Meteor.users().languageKey property? Where would be the best location for it?

Cheers and thanks for the effort!

**Comment by dohomi** [comment]
And additional: is there any good replacement for this kind of route:
```
{{pathFor 'myRoute' _id=currentUser._id
```
I had this in different context very often and its quite tiring introducing a template helper for the ```pathFor```helper setting the data context..

Cheers

**Comment by martinopic** [comment]
Hi @dohomi , I would not define defaultLanguage based on a user languageKey: defaultLanguage is intended to be a fallback when there is not a hint about the user language (which I think is exactly what your "languageKey" is doing). I'd rather use "languageKey" in getLanguage function configuration to get current user language or in a startup block using setLanguage to set the current user language.

As for pathFor it just supports the same configuration as the iron router one with the addition of the "lang" paramenter.

**Comment by martinopic** [comment]
I close this issue as 0.5 version is mature enough not to need "general testing". I'll probably release tomorrow or on tuesday. Please open specific issues for anything else. Thanks for the feedback!
