### ISSUE TITLE
Trouble with default language

### ISSUE THREAD

**Issue by dnish** [yoolab/iron-router-i18n#71]
Hey guys,
I'm having some trouble with the following configuration:

```
 i18n: {
    compulsoryLangCode: true,

    langCodeForDefaultLanguage: false,
}
```

I've enabled the following languages:

```
I18NConf.configure({

languages: ["it", "en", "es", "de"],

defaultLanguage: 'en',


persistLanguage:false

});
```

The problem: The redirect to the browser language doesn't work. In my example, I'm a german user and german is declared as default language on FireFox. The script doesn't redirect me to "myapp.com/de" - it stays on the normal english page "myapp.com". If I set "langCodeForDefaultLanguage" to "true", everything works fine. If I visit "myapp.com", I get automatically redirected to "myapp.com/de" - but then I have also "myapp.com/en" enabled, but I want "myapp.com" as default english page.

**Comment by dnish** [comment]
Just to add more information: It seems like a problem during the startup. I've used the following callback to check the languages:

```
I18NConf.onLanguageChange(function (oldLang, newLang) {

alert(newLang);
});
```

If I open my app, I get 2 alerts with 'en' and 'de' - but the url isn't changing to 'myapp.com/de' - it is still 'myapp.com' with german language on that site. If I execute the setLanguage() function with a timeout, f.e.

//client

```
 Meteor.startup(function() {

  setTimeout(function()
  {
  I18NConf.setLanguage(I18NConf.getNavigatorLanguage());
  },3000);

});
```

I get successfully redirected to 'myapp.com/de' after 3 seconds.

**Comment by martinopic** [comment]
This is not a bug but an intended feature:

if you configure `langCodeForDefaultLanguage: false` you are saying in your case that "en" routes should not have a prefix so when you call `/` (home route without any prefix) it's like if you are calling `/en` therefore you are SETTING language to "en" (i.e. "asking the document in en" in HTTP terms) no matter what your browser says.

I could add a configuration option to override this behavior, that is to always give precedence to navigator language but it wouldn't make much sense not being able to explicitly ask for a page/document in a specific language (would it?).

**Comment by dnish** [comment]
Yeah, but it isn't working. I get the german translation on "/" (home route), not the english one as configured. Also your plugin sets persistLanguage cookie to "en", but the german translation is shown on home route.

I've tried it also with your examples, they having the same problem. My browser has "de" as first language configured, so I've expected, your plugin would redirect me to "/de". 

The redirect works fine, if I set <code>langCodeForDefaultLanguage: true</code>, but then I've also a "/en" route, that I don't want.

**Comment by martinopic** [comment]
Ok, now I understand better. It's a problem with martino:i18n-conf which is now solved in 0.3.3 (just released!). The example is working for me with the new version. I'll release a 1.2.1 with updated dependency to i18n-conf 0.3.3.

**Comment by dnish** [comment]
Hey,
just tried it with example "basic-tap-i18n" and updated versions - still not working here. I've made the following changes (also added a "de.i18n.json"):

init.js

```
I18NConf.configure({
languages: ["it", "en", "es", "de"],
defaultLanguage: 'en',
autoConfLanguage: true
});


Router.configure({
layoutTemplate: 'layout',
   i18n: {

    langCodeForDefaultLanguage: false
}
})
```

If I visit "localhost:3000", I get the english version now, but will not be redirected to the german one (browser language) automatically. If I set <code>langCodeForDefaultLanguage: true</code> I'll get redirected automatically to the german one - but I don't want an extra route ("/en") for default language.

So <code>autoConfLanguage:true</code> isn't working when we have <code>langCodeForDefaultLanguage: false</code>
