### ISSUE TITLE
"already the current language" warnings since v1.2.2

### ISSUE THREAD

**Issue by laurentpayot** [yoolab/iron-router-i18n#75]
Since version 1.2.2 (#74 fix) I get "<i>Warning: asked to change language to [en] but this is already the current language.</i>" console warnings every time I'm moving from one page to another within the English version of my app.

My configuration is (in CoffeeScript, hope you don't mind):

``` coffeescript
I18NConf.configure(
    autoConfLanguage: true
    defaultLanguage: 'en'
    languages: ['en', 'fr']
)

I18NConf.onLanguageChange((oldLang, newLang) ->
    if newLang isnt oldLang
        TAPi18n.setLanguage(newLang)
        T9n.setLanguage(newLang)
)
```

**Comment by erdgrau** [comment]
I have the same problem.

**Comment by Kostanos** [comment]
Same issue here

**Comment by Kostanos** [comment]
+1

**Comment by Xiangshen-Meng** [comment]
+1

**Comment by gregorvand** [comment]
+1

**Comment by sunstorymvp** [comment]
any news here?

**Comment by ipa1981** [comment]
+1

**Comment by martinopic** [comment]
Sorry for reacting so late, version 1.2.3 should solve the problem (it use new 0.3.4 i18n-conf version). Please let me know.

**Comment by gregorvand** [comment]
Fixes for me, thanks!

**Comment by laurentpayot** [comment]
Still having the message when loading/reloading the page (F5) but not between pages anymore so it's good enough for me. Thanks ! :+1:

**Comment by martinopic** [comment]
@laurentpayot you shouldn't have these messages at all, are you sure? maybe if you paste part of your configuration... (or maybe if you can replicate the wrong behaviour by using one of the examples or making an simple example)

**Comment by cedrisk** [comment]
@laurentpayot 
maybe it's because you configure lang selection in a client "Meteor.startup" function

**Comment by martinopic** [comment]
@laurentpayot if this is the case you should just disable language autoconf and have your language configuration. Just remember that in any case you can always get the current language with `I18NConf.getLanguage()` and know if it's the default language or if it was explicitly set with `I18NConf.isLanguageSet()`
